version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: db_postgres
    env_file:
      - .env  
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_net
  
  web:
    build: .
    container_name: app_str
    command: uvicorn src.main:app --host 0.0.0.0 --port 8080
    ports:
      - "8000:8080"
    depends_on:
      - postgres
    networks:
      - app_net  
    env_file:
      - .env       
volumes:
  db-data: 
networks:
  app_net:
